[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run railway-deploy"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[env]
PORT = "$PORT"
NODE_ENV = "production"
